import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Fathir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'CIHUY',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Risol Mayo',
      slug: 'risol-mayo',
      category: 'Makanan',
      image: '/images/risolmayo.jpg',
      price: 2000,
      brand: 'Kantin PM',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'ya risol mayo, pake nanya i lho',
      isFeatured: true,
      banner: '/images/banner1.png',
    },
    {
      name: 'Cendol Cihuy',
      slug: 'Cendol',
      category: 'Minuman',
      image: '/images/cendol.jpg',
      price: 8000,
      brand: 'Kantin AKL',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Yo cendol pada umumnya',
      isFeatured: true,
      banner: '/images/banner2.png',
    },
    {
      name: 'Es Teler',
      slug: 'Es-teler',
      category: 'Minuman',
      image: '/images/esteler.jpg',
      price: 15000,
      brand: 'Kantin MPB',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'TUKUO CAH',
    },
    {
      name: 'Nasi Goreng',
      slug: 'Nasi-Goreng-ngono',
      category: 'Makanan',
      image: '/images/nasigoreng.jpg',
      price: 5000,
      brand: 'Kantin Unit 1',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Yang beli dijamin masuk surga',
    },
    {
      name: 'Mie Ayam Normal',
      slug: 'Mie-Ayam',
      category: 'Makanan',
      image: '/images/mieayam.jpg',
      price: 6000,
      brand: 'Kantin Unit 2',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Enak jarene',
    },
    {
      name: 'Soto biasa',
      slug: 'soto',
      category: 'Makanan',
      image: '/images/soto.jpg',
      price: 3000,
      brand: 'Kantin AKL',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Yo soto too',
    },
  ],
}

export default data
